# $NetBSD$

COLLECTD_PACKAGE=       riemann
COLLECTD_PLUGINS=       write_riemann

COMMENT=                Statistics collection daemon - riemann plugin

.include "../../sysutils/collectd/Makefile.common"

#CONFIGURE_ARGS+=       --enable-write-riemann

.include "../../wip/protobuf-c/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
