# $NetBSD: Makefile,v 1.5 2015/12/05 21:25:48 adam Exp $

VERSION=	0.800
DISTNAME=	authres-${VERSION}
PKGNAME=	${PYPKGPREFIX}-authres-${VERSION}
CATEGORIES=	mail python
MASTER_SITES=	${MASTER_SITE_PYPI:=a/authres/}

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://pypi.python.org/pypi/authres
COMMENT=	Python implementation of the RFC 5451/7001
LICENSE=	apache-2.0

.include "../../lang/python/distutils.mk"
.include "../../mk/bsd.pkg.mk"
