# $NetBSD: Makefile,v 1.7 2012/10/23 17:19:00 asau Exp $
#

DISTNAME=	puf-1.0.0
CATEGORIES=	net
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=puf/}

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://puf.sourceforge.net/
COMMENT=	Parallel URL fetcher
LICENSE=	gnu-gpl-v2

GNU_CONFIGURE=	YES

.include "../../mk/bsd.pkg.mk"
