# $NetBSD$

DISTNAME=	pv-1.6.0
CATEGORIES=	misc
MASTER_SITES=	https://www.ivarch.com/programs/sources/
EXTRACT_SUFX=	.tar.bz2

MAINTAINER=	pkgsrc-maintainers@netbsd.org
HOMEPAGE=	https://www.ivarch.com/programs/sources/
COMMENT=	Monitor data progress through a pipe
LICENSE=	artistic-2.0

USE_TOOLS+=	gmake

GNU_CONFIGURE=	yes

.include "../../mk/bsd.pkg.mk"
