# $NetBSD$

DISTNAME=	tablib-0.11.2
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	textproc
MASTER_SITES=	${MASTER_SITE_PYPI:=t/tablib/}

MAINTAINER=	root@zta.lk
HOMEPAGE=	https://pypi.python.org/packages/source/t/tablib/
COMMENT=	Format agnostic tabular data library (XLS, JSON, YAML, CSV)
LICENSE=	mit

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
